### ISSUE TITLE
Staff: Profile Lookup and Editing - questions

### ISSUE THREAD

**Issue by katedlu** [yvesshum/bikeshop-webapp#106]
1. Should Merits/Demerits be in the profile view?
2. Why is a new field a "non-standard" field when it is added to required fields through the admin panel? (see 2 pics attached)
<img width="680" alt="Screen Shot 2020-07-04 at 3 27 33 PM" src="https://user-images.githubusercontent.com/30165182/86521883-07066a00-be0b-11ea-9fc4-34bd6d369155.png">

when editing:
<img width="507" alt="Screen Shot 2020-07-04 at 3 39 08 PM" src="https://user-images.githubusercontent.com/30165182/86522105-7f6e2a80-be0d-11ea-8544-340b9de2bbe9.png">

**Comment by vlagrassa** [comment]
If we want to do live updates to data at a later time, it would probably be in `ProfileLookup.vue` and `ProfileLookupAndEditing.vue`, not `ProfileFields.vue`.
