### ISSUE TITLE
Staff: Profile Lookup and Editing - Edit modal fixes

### ISSUE THREAD

**Issue by katedlu** [yvesshum/bikeshop-webapp#134]
- [x] When clicking "Reset Changes" at the bottom of the edit profile modal, the hidden fields (Merits and Demerits) are not reset
- [x] We can prob remove the "x" on the left side of the hidden fields edit inputs
- [x] Gender radio button does not show which one was chosen

**Comment by vlagrassa** [comment]
Part 1 should be fixed by commit d531b10a70d25fa2fa7f7610a8e82bcbed9ef5ee

**Comment by vlagrassa** [comment]
Part 2 is addressed by commit dfc7c85b9cf0549517dd6d1d517a206d681cf73f
